[package]
name = "talos"
version = "0.1.0"
authors = ["Nick Gerakines <nick.gerakines@gmail.com>"]
edition = "2018"

[dependencies]
iced = { version = "0.2", features = ["tokio", "debug"] }
rand = "0.7"
